DROP DATABASE IF EXISTS FINANCIATION;
CREATE DATABASE FINANCIATION;
USE FINANCIATION;

CREATE TABLE INTENDENTES
(
    ID       INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE   VARCHAR(70),
    APELLIDO VARCHAR(70)
);

CREATE TABLE PARTIDOS_POLITICOS
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE DEPARTAMENTOS_CIUDAD
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(70),
    DESCRIPCION TEXT
);

CREATE TABLE ESTADOS_DE_VISITA
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE DIRECCIONES
(
    ID     INT AUTO_INCREMENT PRIMARY KEY,
    CALLE  VARCHAR(70),
    ALTURA INT
);

CREATE TABLE LOGOS
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE ASESORADOS
(
    ID       INT AUTO_INCREMENT PRIMARY KEY,
    CUIL     BIGINT,
    NOMBRE   VARCHAR(70),
    APELLIDO VARCHAR(70)
);

CREATE TABLE FAQs
(
    ID       INT AUTO_INCREMENT PRIMARY KEY,
    PREGUNTA TEXT
);

CREATE TABLE DEPARTAMENTOS_DEL_MINISTERIO
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE ROLES
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE ESTADOS_DE_USUARIO
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE ESTADOS_DE_VERIFICACION_DE_USUARIO
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE CONVENIOS
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE PATENTES_DE_VEHICULOS
(
    ID      INT AUTO_INCREMENT PRIMARY KEY,
    PATENTE VARCHAR(7)
);

CREATE TABLE MARCAS_DE_VEHICULOS
(
    ID     INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(30)
);

CREATE TABLE MODELOS_DE_VEHICULOS
(
    ID       INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE   VARCHAR(50),
    ID_MARCA INT,
    CONSTRAINT `MODELO_VEHICULO->MARCA_VEHICULO` FOREIGN KEY (ID_MARCA) REFERENCES MARCAS_DE_VEHICULOS (ID)
);

CREATE TABLE VEHICULOS
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    ID_PATENTE INT,
    ID_MARCA   INT,
    ID_MODELO  INT,
    CONSTRAINT `VEHICULO->PATENTE_VEHICULO` FOREIGN KEY (ID_PATENTE) REFERENCES PATENTES_DE_VEHICULOS (ID),
    CONSTRAINT `VEHICULO->MARCA_VEHICULO` FOREIGN KEY (ID_MARCA) REFERENCES MARCAS_DE_VEHICULOS (ID),
    CONSTRAINT `VEHICULO->MODELO_VEHICULO` FOREIGN KEY (ID_MODELO) REFERENCES MODELOS_DE_VEHICULOS (ID)
);


CREATE TABLE USUARIOS
(
    ID                        INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_DE_USUARIO         VARCHAR(30),
    CUIL                      BIGINT,
    CONTRASEÑA                MEDIUMBLOB,
    FOTO_DE_PERFIL            LONGBLOB,
    ID_ROL                    INT,
    ID_ESTADO_DE_VERIFICACION INT,
    ID_ESTADO_DE_USUARIO      INT,
    CONSTRAINT `USUARIO->ROL` FOREIGN KEY (ID_ROL) REFERENCES ROLES (ID),
    CONSTRAINT `USUARIO->ESTADO_DE_VERIFICACION_DE_USUARIO` FOREIGN KEY (ID_ESTADO_DE_VERIFICACION) REFERENCES ESTADOS_DE_VERIFICACION_DE_USUARIO (ID),
    CONSTRAINT `USUARIO->ESTADO_DE_USUARIO` FOREIGN KEY (ID_ESTADO_DE_USUARIO) REFERENCES ESTADOS_DE_USUARIO (ID)
);

CREATE TABLE LOCALIDADES
(
    ID              INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE          VARCHAR(70),
    ID_DEPARTAMENTO INT,
    CONSTRAINT `LOCALIDAD->DEPARTAMENTO_CIUDAD` FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS_CIUDAD (ID)
);

CREATE TABLE REFERENTES_CONTACTADOS
(
    ID       INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE   VARCHAR(70),
    APELLIDO VARCHAR(70)
);

CREATE TABLE GRUPOS
(
    ID     INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(70)
);

CREATE TABLE ESTADO_DE_CONSULTA
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE VISITAS
(
    ID                      INT AUTO_INCREMENT PRIMARY KEY,
    FLYER                   BOOL,
    DISTANCIA               INT,
    TIEMPO_DE_VIAJE         INT,
    FECHA_DE_VISITA         DATE,
    REGISTRO_CIVIL          BOOL,
    HOSPEDAJE               BOOL,
    FONDO_DE_MODERNIZACION  BOOL,
    HORARIO_INICIO          DATETIME,
    HORARIO_FINALIZACION    DATETIME,
    NOMBRE_LUGAR            VARCHAR(70),
    ID_LOCALIDAD            INT,
    ID_GRUPO                INT,
    ID_ESTADO_DE_VISITA     INT,
    ID_CONVENIO_FIRMADO     INT,
    ID_REFERENTE_CONTACTADO INT,
    ID_DIRECCION            INT,
    ID_LOGO                 INT,
    CONSTRAINT `VISITA->LOCALIDAD` FOREIGN KEY (ID_LOCALIDAD) REFERENCES LOCALIDADES (ID),
    CONSTRAINT `VISITA->GRUPO` FOREIGN KEY (ID_GRUPO) REFERENCES GRUPOS (ID),
    CONSTRAINT `VISITA->ESTADO_DE_VISITA` FOREIGN KEY (ID_ESTADO_DE_VISITA) REFERENCES ESTADOS_DE_VISITA (ID),
    CONSTRAINT `VISITA->CONVENIO_FIRMADO` FOREIGN KEY (ID_CONVENIO_FIRMADO) REFERENCES CONVENIOS (ID),
    CONSTRAINT `VISITA->REFERENTE_CONTACTADO` FOREIGN KEY (ID_REFERENTE_CONTACTADO) REFERENCES REFERENTES_CONTACTADOS (ID),
    CONSTRAINT `VISITA->DIRECCION` FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCIONES (ID),
    CONSTRAINT `VISITA->LOGO` FOREIGN KEY (ID_LOGO) REFERENCES LOGOS (ID)
);

CREATE TABLE CONSULTAS
(
    ID                         INT AUTO_INCREMENT PRIMARY KEY,
    ID_VISITA                  INT,
    ID_ASESORADO               INT,
    ID_ASESOR                  INT,
    ID_DEPARTAMENTO_MINISTERIO INT,
    ID_FAQ                     INT,
    ID_ESTADO INT,
    CONSTRAINT `CONSULTA->VISITA` FOREIGN KEY (ID_VISITA) REFERENCES VISITAS (ID),
    CONSTRAINT `CONSULTA->ASESORADO` FOREIGN KEY (ID_ASESORADO) REFERENCES ASESORADOS (ID),
    CONSTRAINT `CONSULTA->ASESOR` FOREIGN KEY (ID_ASESOR) REFERENCES USUARIOS (ID),
    CONSTRAINT `CONSULTA->DEPARTAMENTO_DEL_MINISTERIO` FOREIGN KEY (ID_DEPARTAMENTO_MINISTERIO) REFERENCES DEPARTAMENTOS_DEL_MINISTERIO (ID),
    CONSTRAINT `CONSULTA->FAQ` FOREIGN KEY (ID_FAQ) REFERENCES FAQs (ID),
    CONSTRAINT `CONSULTA->ESTADO_CONSULTA` FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_DE_CONSULTA (ID)
);

CREATE TABLE ASESORES
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT,
    ID_GRUPO   INT,
    CONSTRAINT `ASESOR->USUARIO` FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID),
    CONSTRAINT `ASESOR->GRUPO` FOREIGN KEY (ID_GRUPO) REFERENCES GRUPOS (ID),
    CONSTRAINT `ASESOR` UNIQUE (ID_USUARIO, ID_GRUPO)
);

CREATE TABLE COORDINADORES
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT,
    ID_GRUPO   INT,
    CONSTRAINT `COORDINADOR->USUARIO` FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID),
    CONSTRAINT `COORDINADOR->GRUPO` FOREIGN KEY (ID_GRUPO) REFERENCES GRUPOS (ID),
    CONSTRAINT `COORDINADOR` UNIQUE (ID_USUARIO)
);

CREATE TABLE TELEFONOS_REFERENTES_CONTACTADOS
(
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    TELEFONO     BIGINT,
    ID_REFERENTE INT,
    CONSTRAINT `TELEFONOS_REFERENTES_CONTACTADOS->REFERENTE_CONTACTADO` FOREIGN KEY (ID_REFERENTE) REFERENCES REFERENTES_CONTACTADOS (ID)
);

CREATE TABLE EMAILS_REFERENTES_CONTACTADOS
(
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    MAIL         VARCHAR(100),
    ID_REFERENTE INT,
    CONSTRAINT `EMAIL_REFERENTES_CONTACTADOS->REFERENTE_CONTACTADO` FOREIGN KEY (ID_REFERENTE) REFERENCES REFERENTES_CONTACTADOS (ID)
);

CREATE TABLE TELEFONOS_INTENDENTES
(
    ID            INT AUTO_INCREMENT PRIMARY KEY,
    TELEFONO      BIGINT,
    ID_INTENDENTE INT,
    CONSTRAINT `TELEFONOS_INTENDENTES->INTENDENTE` FOREIGN KEY (ID_INTENDENTE) REFERENCES INTENDENTES (ID)
);

CREATE TABLE EMAILS_INTENDENTES
(
    ID            INT AUTO_INCREMENT PRIMARY KEY,
    MAIL          VARCHAR(100),
    ID_INTENDENTE INT,
    CONSTRAINT `EMAIL_INTENDENTES->INTENDENTE` FOREIGN KEY (ID_INTENDENTE) REFERENCES INTENDENTES (ID)
);

CREATE TABLE EMAILS_USUARIOS
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    MAIL       VARCHAR(100),
    ID_USUARIO INT,
    CONSTRAINT `EMAILS_USUARIOS->USUARIO` FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID)
);