# Generated by Django 4.2.1 on 2023-06-03 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=2550, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('ssn', models.BigIntegerField()),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('phone_number', models.BigIntegerField()),
                ('profile_picture', models.ImageField(default=None, upload_to='djangoapp/images/profile_pictures/')),
                ('groups', models.ManyToManyField(blank=True,
                                                  help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                                                  related_name='user_set', related_query_name='user', to='auth.group',
                                                  verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=70)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Advised',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.BigIntegerField()),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CityDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactedReferrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('id_department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                                    to='financiationAPI.citydepartment')),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='MinistryDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PoliticParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id_brand',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financiationAPI.vehiclebrand')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='VisitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flyer', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('travel_time', models.IntegerField()),
                ('visit_date', models.DateField()),
                ('civil_registration', models.IntegerField()),
                ('accommodation', models.IntegerField()),
                ('modernization_fund', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('place_name', models.CharField(max_length=70)),
                ('id_address',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financiationAPI.address')),
                ('id_agreement', models.ManyToManyField(to='financiationAPI.agreement')),
                ('id_contacted_referrer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                                            to='financiationAPI.contactedreferrer')),
                ('id_group',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financiationAPI.group')),
                ('id_locality',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financiationAPI.locality')),
                ('id_logo', models.ManyToManyField(to='financiationAPI.logo')),
                ('id_visit_status',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financiationAPI.visitstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_brand',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financiationAPI.vehiclebrand')),
                ('id_model',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financiationAPI.vehiclemodel')),
                ('id_plate',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financiationAPI.vehicleplate')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_advised',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financiationAPI.advised')),
                ('id_advisor',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financiationAPI.advisor')),
                ('id_faq', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financiationAPI.faq')),
                ('id_ministry_department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                                             to='financiationAPI.ministrydepartment')),
                ('id_status',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financiationAPI.requeststatus')),
                ('id_visit',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financiationAPI.visit')),
            ],
        ),
        migrations.CreateModel(
            name='MayorPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('id_mayor',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financiationAPI.mayor')),
            ],
        ),
        migrations.CreateModel(
            name='MayorEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=100)),
                ('id_mayor',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financiationAPI.mayor')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_group',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financiationAPI.group')),
                ('id_user',
                 models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactedReferrerPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('id_contacted_referrer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                                            to='financiationAPI.contactedreferrer')),
            ],
        ),
        migrations.CreateModel(
            name='ContactedReferrerEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=100)),
                ('id_contacted_referrer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                                            to='financiationAPI.contactedreferrer')),
            ],
        ),
        migrations.AddField(
            model_name='advisor',
            name='id_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financiationAPI.group'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='id_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='financiationAPI.role'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='id_user_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='financiationAPI.userstatus'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.',
                                         related_name='user_set', related_query_name='user', to='auth.permission',
                                         verbose_name='user permissions'),
        ),
    ]
