# Generated by Django 4.2.1 on 2023-08-20 00:59

import requests
from django.db import migrations, transaction
from psycopg2 import IntegrityError


def get_city_departments(app, *args):
    try:
        with transaction.atomic():
            CityDepartment = app.get_model('financiationAPI', 'CityDepartment')
            URL = 'https://apis.datos.gob.ar/georef/api/departamentos?provincia=córdoba&campos=nombre&max=50'
            r = requests.get(URL)
            data = r.json()
            departamentos = []
            for d in data.get('departamentos'):
                departamento = CityDepartment(id=d.get("id"), name=d.get("nombre"), description=d.get("nombre"))
                departamentos.append(departamento)
            CityDepartment.objects.bulk_create(departamentos)
    except IntegrityError:
        print("--------------ERROR--------------")


def get_localities(app, *args):
    try:
        with transaction.atomic():
            Location = app.get_model('financiationAPI', 'Location')
            URL = "https://apis.datos.gob.ar/georef/api/localidades?provincia=Córdoba&campos=nombre,departamento&max=1000"
            r = requests.get(URL)
            data = r.json()
            localidades = []
            for d in data.get("localidades"):
                localidad = Location(name=d.get("nombre"), department_id=d.get("departamento").get("id"))
                localidades.append(localidad)
            Location.objects.bulk_create(localidades)
    except IntegrityError:
        print("--------------ERROR--------------")


class Migration(migrations.Migration):
    dependencies = [
        ('financiationAPI', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(get_city_departments),
        migrations.RunPython(get_localities)
    ]
