# Generated by Django 4.2.1 on 2023-06-13 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('financiationAPI', '0003_get_localities_and_departments'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO \"financiationAPI_role\" (name, description) VALUES ('Referente', 'El rol de referente es aquel que constestara las consultas que no puedan los Asesores'), ('Secretario/a', 'El rol de secretario/a es el encargado de agendar visitas y proveer informacion sobre ella'), ('Administrador', 'Este rol es capaz de hacer cualquier cosa en el sistema')"),
        migrations.RunSQL(
            "INSERT INTO \"financiationAPI_faq\" (faq) VALUES ('Impresion Cedulón 2023'), ('Asesoramiento de gestiones online'), ('Consulta y regularizacion de deuda'), ('Pago online con tarjetas de debito y credito'), ('Adhesion a debito automatico'), ('Consulta de extenciones impositivas'), ('Tramite de DNI y Pasaporte'), ('Inicio de tramite de partidas de nacimiento y matrimonio'), ('Jubilaciones o pensiones'), ('Futuros beneficiarios'), ('Subsidios por fallecimiento o seguros'), ('Historia Laboral'), ('Creacion de cuentas de Ciudadano Digital Nivel 2'), ('Recuperacion de cuentas'), ('Actualizacion de mails'), ('Inscripcion de vivienda como Bien de Familia'), ('No conoce los cales de atencion habilitados'), ('No logro realizar la gestion via web/online'), ('No dispone de acceso a tecnologia/internet'), ('Prefiere atencion presencial')"),
        migrations.RunSQL(
            "INSERT INTO \"financiationAPI_ministrydepartment\" (name, description) VALUES ('Rentas Cordoba', 'Direccion General de Rentas de la Provincia de Cordoba'), ('Registro Civil', 'Registro Civil'), ('Catastro', 'Datos de inmuebles'), ('Caja de Jubilaciones', 'Caja de Jubilaciones, Pensiones y Retiros de la Provincia de Córdoba'), ('CiDi', 'Ciudadano Digital'), ('IPJ', 'Inspecion de Personas Juridicas'), ('Registro de la Propiedad', 'Registro de la Propiedad')"),
        migrations.RunSQL(
            "INSERT INTO \"financiationAPI_visitstatus\" (name, description) VALUES ('No Confirmada', 'La visita no se confirmo todavia'), ('Pendiente', 'La visita esta confirmada pero todavia no se realizo'), ('En proceso', 'La visita esta siendo realizada'), ('Finalizada', 'La visita se realizo')"),
        migrations.RunSQL(
            "INSERT INTO \"financiationAPI_requeststatus\" (name, description)  VALUES ('Resuelta', 'La consulta ha sido resuelta'), ('No resuelta', 'La consulta ni ha sido resuelta'), ('Pendiente', 'La consulta esta en proceso')"),
        migrations.RunSQL(
            "INSERT INTO \"financiationAPI_userstatus\" (name, description) VALUES ('Disponible', 'El usuario esta disponile para una visita'), ('Ocupado', 'El usuario no esta disponible')")

    ]
