# Generated by Django 4.2.1 on 2023-08-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiationAPI', '0003_data_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
