# Generated by Django 4.2.1 on 2023-08-21 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financiationAPI', '0004_alter_useraccount_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='datatime',
            new_name='request_datatime',
        ),
    ]
