# Generated by Django 4.2.1 on 2023-06-13 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('financiationAPI', '0004_populate_database'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO financiationAPI_address (street, number) VALUES ('Loncoche', 8136), ('Hualil', 1880), ('Hilario Ascasubi', 330)"),
        migrations.RunSQL(
            "INSERT INTO financiationAPI_advised (ssn, first_name, last_name) VALUES (2011111110, 'Elvio', 'Marchisone'), (20222222220, 'Carlos', 'Marchisone'), (20333333330, 'Oscar', 'Marchisone')"),
        migrations.RunSQL(
            "INSERT INTO financiationAPI_agreement (name, description) VALUES ('IAU', 'IAU'), ('MUC', 'MUC')"),
        migrations.RunSQL(
            "INSERT INTO financiationAPI_contactedreferrer (first_name, last_name) VALUES ('Yanina', 'Ribone'), ('Laura', 'Ribone'), ('Elisa', 'Ribone')"),
        migrations.RunSQL(
            "INSERT INTO financiationAPI_contactedreferreremail (mail, id_contacted_referrer_id) VALUES ('y.ribone@gmail.com', 1), ('l.ribone@gmail.com', 2), ('e.ribone@gmail.com', 3)"),
        migrations.RunSQL(
            "INSERT INTO financiationAPI_contactedreferrerphone (phone, id_contacted_referrer_id) VALUES (3511111111, 1), (3512222222, 2), (3513333333, 3)"),
        migrations.RunSQL(
            "INSERT INTO financiationAPI_logo (name, description) VALUES ('Minsterio de Finanzas', 'Minsterio de Finanzas'), ('CiDi', 'CiDi'), ('Gob. de la Prov. de Cordoba', 'Gob. de la Prov. de Cordoba')"),
        migrations.RunSQL(
            "INSERT INTO financiationAPI_mayor (first_name, last_name) VALUES ('Martin', 'Llaryora'), ('Juan', 'Schiaretti'), ('Horacio', 'Larreta')"),
        migrations.RunSQL(
            "INSERT INTO financiationAPI_mayoremail (mail, id_mayor_id) VALUES ('m.llaryora@gmail.com', 1), ('j.schiaretti@gmail.com', 2), ('h.larreta@gmail.com', 3)"),
        migrations.RunSQL(
            "INSERT INTO financiationAPI_mayorphone (phone, id_mayor_id) VALUES (3514444444, 1), (3515555555, 2), (3516666666, 3)"),
        migrations.RunSQL(
            "INSERT INTO financiationAPI_politicparty (name, description) VALUES ('UCR', 'UCR'), ('HPC', 'HPC'), ('VECINAL', 'VECINAL')"),
        migrations.RunSQL("INSERT INTO financiationAPI_group (name) VALUES ('Grupo 1'), ('Grupo 2'), ('Grupo 3')"),
    ]
