# Generated by Django 4.2.1 on 2023-11-08 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financiationAPI', '0004_alter_visit_travel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='travel_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='financiationAPI.location'),
        ),
    ]
