# Generated by Django 4.2.1 on 2023-08-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiationAPI', '0005_rename_datatime_request_request_datatime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_picture',
            field=models.BinaryField(editable=True),
        ),
    ]
