# Generated by Django 4.2.1 on 2023-06-21 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financiationAPI', '0006_alter_useraccount_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='faq',
            new_name='name',
        ),
    ]
