# Generated by Django 4.2.1 on 2023-09-08 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("financiationAPI", "0006_alter_useraccount_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mayoremail",
            name="mayor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="financiationAPI.mayor"
            ),
        ),
        migrations.AlterField(
            model_name="mayorphone",
            name="mayor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="financiationAPI.mayor"
            ),
        ),
    ]
