# Generated by Django 4.2.1 on 2023-06-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiationAPI', '0007_rename_faq_faq_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_picture',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
