# Generated by Django 4.2.1 on 2023-09-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiationAPI', '0008_alter_visit_mayor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_picture',
            field=models.BinaryField(blank=True, editable=True),
        ),
    ]
