# Generated by Django 4.2.1 on 2023-06-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiationAPI', '0008_alter_useraccount_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='id_ministry_department',
            field=models.ManyToManyField(to='financiationAPI.ministrydepartment'),
        ),
    ]
