# Generated by Django 4.2.1 on 2023-09-20 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("financiationAPI", "0009_alter_useraccount_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="advisor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="financiationAPI.advisor",
            ),
        ),
    ]
