# Generated by Django 4.2.1 on 2023-08-01 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('financiationAPI', '0009_faq_id_ministry_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
