# Generated by Django 4.2.1 on 2023-09-20 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("financiationAPI", "0010_alter_request_advisor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="advisor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="financiationAPI.advisor",
            ),
        ),
    ]
