# Generated by Django 4.2.1 on 2023-09-20 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financiationAPI', '0012_alter_request_advisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('observation', models.TextField(blank=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='mayor',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='financiationAPI.location'),
        ),
        migrations.AddField(
            model_name='request',
            name='observation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financiationAPI.advisor'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='ministry_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financiationAPI.division'),
        ),
        migrations.DeleteModel(
            name='MinistryDepartment',
        ),
    ]
