# Generated by Django 4.2.1 on 2023-08-13 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('financiationAPI', '0013_users'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO \"financiationAPI_coordinator\" (id_group_id, id_user_id)"
                          "VALUES (1, 1),"
                          "(1, 2),"
                          "(2, 3),"
                          "(2, 4),"
                          "(3, 5),"
                          "(3, 6),"
                          "(2, 1),"
                          "(3, 1)"),

        migrations.RunSQL("INSERT INTO \"financiationAPI_advisor\" (id_group_id, id_user_id)"
                          "VALUES (1, 7),"
                          "(1, 8),"
                          "(1, 9),"
                          "(1, 10),"
                          "(2, 11),"
                          "(2, 12),"
                          "(2, 13),"
                          "(2, 14),"
                          "(3, 15),"
                          "(3, 16),"
                          "(3, 17),"
                          "(3, 18)")
    ]
