# Generated by Django 4.2 on 2023-04-21 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=70)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Advised',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.BigIntegerField()),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CityDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactedReferrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('id_department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.citydepartment')),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='MinistryDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PoliticParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('ssn', models.BigIntegerField()),
                ('password', models.TextField()),
                ('profile_picture', models.TextField()),
                ('id_role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.role')),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserVerifiedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id_brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.vehiclebrand')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='VisitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flyer', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('travel_time', models.IntegerField()),
                ('visit_date', models.DateField()),
                ('civil_registration', models.IntegerField()),
                ('accommodation', models.IntegerField()),
                ('modernization_fund', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('place_name', models.CharField(max_length=70)),
                ('id_address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.address')),
                ('id_agreement', models.ManyToManyField(to='djangoapp.agreement')),
                ('id_contacted_referrer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.contactedreferrer')),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.group')),
                ('id_locality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.locality')),
                ('id_logo', models.ManyToManyField(to='djangoapp.logo')),
                ('id_visit_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.visitstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.vehiclebrand')),
                ('id_model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.vehiclemodel')),
                ('id_plate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.vehicleplate')),
            ],
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=100)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='id_user_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.userstatus'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_verified_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.userverifiedstatus'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_advised', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.advised')),
                ('id_advisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.advisor')),
                ('id_faq', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.faq')),
                ('id_ministry_department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.ministrydepartment')),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.requeststatus')),
                ('id_visit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.visit')),
            ],
        ),
        migrations.CreateModel(
            name='MayorPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('id_mayor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.mayor')),
            ],
        ),
        migrations.CreateModel(
            name='MayorEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=100)),
                ('id_mayor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.mayor')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.group')),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='ContactedReferrerPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('id_contacted_referrer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.contactedreferrer')),
            ],
        ),
        migrations.CreateModel(
            name='ContactedReferrerEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=100)),
                ('id_contacted_referrer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.contactedreferrer')),
            ],
        ),
        migrations.AddField(
            model_name='advisor',
            name='id_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.group'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.user'),
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=2550, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('ssn', models.BigIntegerField()),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
