# Generated by Django 4.2 on 2023-04-20 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=70)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Advised',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.BigIntegerField()),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactedReferrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('id_department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.citydepartment')),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='MinistryDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('ssn', models.BigIntegerField()),
                ('password', models.TextField()),
                ('profile_picture', models.TextField(blank=True, null=True)),
                ('id_role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.roles')),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserVerifiedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id_brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.vehiclebrand')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='VisitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flyer', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('travel_time', models.IntegerField()),
                ('visit_date', models.DateField()),
                ('civil_registration', models.IntegerField()),
                ('accommodation', models.IntegerField()),
                ('modernization_fund', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('place_name', models.CharField(max_length=70)),
                ('id_address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.address')),
                ('id_agreement', models.ManyToManyField(to='djangoapp.agreement')),
                ('id_contacted_referrer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.contactedreferrer')),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.group')),
                ('id_locality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.locality')),
                ('id_logo', models.ManyToManyField(to='djangoapp.logo')),
                ('id_visit_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.visitstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.vehiclebrand')),
                ('id_model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.vehiclemodel')),
                ('id_plate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.vehicleplate')),
            ],
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=100)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='id_user_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.userstatus'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_verified_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.userverifiedstatus'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_advised', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.advised')),
                ('id_advisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.advisor')),
                ('id_faq', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.faq')),
                ('id_ministry_department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.ministrydepartment')),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.requeststatus')),
                ('id_visit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.visit')),
            ],
        ),
        migrations.CreateModel(
            name='MayorPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('id_mayor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.mayor')),
            ],
        ),
        migrations.CreateModel(
            name='MayorEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=100)),
                ('id_mayor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.mayor')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.group')),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='ContactedReferrerPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('id_contacted_referrer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.contactedreferrer')),
            ],
        ),
        migrations.CreateModel(
            name='ContactedReferrerEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=100)),
                ('id_contacted_referrer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.contactedreferrer')),
            ],
        ),
        migrations.AddField(
            model_name='advisor',
            name='id_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.group'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.user'),
        ),
    ]
