# Generated by Django 4.2 on 2023-05-10 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.role'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id_user_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.userstatus'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id_verified_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.userverifiedstatus'),
        ),
    ]
