# Generated by Django 4.2 on 2023-05-16 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO djangoapp_role (name, description) VALUES ('Referente', 'El rol de referente es aquel que constestara las consultas que no puedan los Asesores'), ('Secretario/a', 'El rol de secretario/a es el encargado de agendar visitas y proveer informacion sobre ella'), ('Administrador', 'Este rol es capaz de hacer cualquier cosa en el sistema')"),

        migrations.RunSQL(
            "INSERT INTO djangoapp_faq (faq) VALUES ('Impresion Cedulón 2023'), ('Asesoramiento de gestiones online'), ('Consulta y regularizacion de deuda'), ('Pago online con tarjetas de debito y credito'), ('Adhesion a debito automatico'), ('Consulta de extenciones impositivas'), ('Tramite de DNI y Pasaporte'), ('Inicio de tramite de partidas de nacimiento y matrimonio'), ('Jubilaciones o pensiones'), ('Futuros beneficiarios'), ('Subsidios por fallecimiento o seguros'), ('Historia Laboral'), ('Creacion de cuentas de Ciudadano Digital Nivel 2'), ('Recuperacion de cuentas'), ('Actualizacion de mails'), ('Inscripcion de vivienda como Bien de Familia'), ('No conoce los cales de atencion habilitados'), ('No logro realizar la gestion via web/online'), ('No dispone de acceso a tecnologia/internet'), ('Prefiere atencion presencial')"),

        migrations.RunSQL(
            "INSERT INTO djangoapp_ministrydepartment (name, description) VALUES ('Rentas Cordoba', 'Direccion General de Rentas de la Provincia de Cordoba'), ('Registro Civil', 'Registro Civil'), ('Catastro', 'Datos de inmuebles'), ('Caja de Jubilaciones', 'Caja de Jubilaciones, Pensiones y Retiros de la Provincia de Córdoba'), ('CiDi', 'Ciudadano Digital'), ('IPJ', 'Inspecion de Personas Juridicas'), ('Registro de la Propiedad', 'Registro de la Propiedad')"),

        migrations.RunSQL(
            "INSERT INTO djangoapp_visitstatus (name, description) VALUES ('No Confirmada', 'La visita no se confirmo todavia'), ('Pendiente', 'La visita esta confirmada pero todavia no se realizo'), ('En proceso', 'La visita esta siendo realizada'), ('Finalizada', 'La visita se realizo')"),

        migrations.RunSQL(
            "INSERT INTO djangoapp_requeststatus (name, description) VALUES ('Resuelta', 'La consulta ha sido resuelta'), ('No resuelta', 'La consulta ni ha sido resuelta')")

    ]

    """
     migrations.RunSQL("INSERT INTO djangoapp_citydepartment (name, description) ")
     migrations.RunSQL("INSERT INTO djangoapp_locality (name, department_id)")
     migrations.RunSQL("INSERT INTO djangoapp_mayor" (first_name, last_name)")
     migrations.RunSQL("INSERT INTO djangoapp_logo" (name, description)")
     migrations.RunSQL("INSERT INTO djangoapp_politicparty)
     """
