# Generated by Django 4.2 on 2023-04-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesorados',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cuil', models.BigIntegerField(blank=True, db_column='CUIL', null=True)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=70, null=True)),
                ('apellido', models.CharField(blank=True, db_column='APELLIDO', max_length=70, null=True)),
            ],
            options={
                'db_table': 'asesorados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asesores',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'asesores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'consultas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Convenios',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='DESCRIPCION', null=True)),
            ],
            options={
                'db_table': 'convenios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coordinadores',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'coordinadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartamentosCiudad',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=70, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='DESCRIPCION', null=True)),
            ],
            options={
                'db_table': 'departamentos_ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartamentosDelMinisterio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='DESCRIPCION', null=True)),
            ],
            options={
                'db_table': 'departamentos_del_ministerio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('calle', models.CharField(blank=True, db_column='CALLE', max_length=70, null=True)),
                ('altura', models.IntegerField(blank=True, db_column='ALTURA', null=True)),
            ],
            options={
                'db_table': 'direcciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailsReferentesContactados',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('mail', models.CharField(blank=True, db_column='MAIL', max_length=100, null=True)),
            ],
            options={
                'db_table': 'emails_referentes_contactados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailsUsuarios',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('mail', models.CharField(blank=True, db_column='MAIL', max_length=100, null=True)),
            ],
            options={
                'db_table': 'emails_usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosDeUsuario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='DESCRIPCION', null=True)),
            ],
            options={
                'db_table': 'estados_de_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosDeVerificacionDeUsuario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='DESCRIPCION', null=True)),
            ],
            options={
                'db_table': 'estados_de_verificacion_de_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosDeVisita',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='DESCRIPCION', null=True)),
            ],
            options={
                'db_table': 'estados_de_visita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('pregunta', models.TextField(blank=True, db_column='PREGUNTA', null=True)),
            ],
            options={
                'db_table': 'faqs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=70, null=True)),
            ],
            options={
                'db_table': 'grupos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Intendentes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=70, null=True)),
                ('apellido', models.CharField(blank=True, db_column='APELLIDO', max_length=70, null=True)),
            ],
            options={
                'db_table': 'intendentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=70, null=True)),
            ],
            options={
                'db_table': 'localidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='DESCRIPCION', null=True)),
            ],
            options={
                'db_table': 'logos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarcasDeVehiculos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=30, null=True)),
            ],
            options={
                'db_table': 'marcas_de_vehiculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelosDeVehiculos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=50, null=True)),
            ],
            options={
                'db_table': 'modelos_de_vehiculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartidosPoliticos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='DESCRIPCION', null=True)),
            ],
            options={
                'db_table': 'partidos_politicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatentesDeVehiculos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('patente', models.CharField(blank=True, db_column='PATENTE', max_length=7, null=True)),
            ],
            options={
                'db_table': 'patentes_de_vehiculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReferentesContactados',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=70, null=True)),
                ('apellido', models.CharField(blank=True, db_column='APELLIDO', max_length=70, null=True)),
            ],
            options={
                'db_table': 'referentes_contactados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='DESCRIPCION', null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelefonosReferentesContactados',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('telefono', models.BigIntegerField(blank=True, db_column='TELEFONO', null=True)),
            ],
            options={
                'db_table': 'telefonos_referentes_contactados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre_de_usuario', models.CharField(blank=True, db_column='NOMBRE_DE_USUARIO', max_length=30, null=True)),
                ('cuil', models.BigIntegerField(blank=True, db_column='CUIL', null=True)),
                ('contrasenia', models.TextField(blank=True, db_column='CONTRASENIA', null=True)),
                ('foto_de_perfil', models.TextField(blank=True, db_column='FOTO_DE_PERFIL', null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vehiculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('flyer', models.IntegerField(blank=True, db_column='FLYER', null=True)),
                ('distancia', models.IntegerField(blank=True, db_column='DISTANCIA', null=True)),
                ('tiempo_de_viaje', models.IntegerField(blank=True, db_column='TIEMPO_DE_VIAJE', null=True)),
                ('fecha_de_visita', models.DateField(blank=True, db_column='FECHA_DE_VISITA', null=True)),
                ('registro_civil', models.IntegerField(blank=True, db_column='REGISTRO_CIVIL', null=True)),
                ('hospedaje', models.IntegerField(blank=True, db_column='HOSPEDAJE', null=True)),
                ('fondo_de_modernizacion', models.IntegerField(blank=True, db_column='FONDO_DE_MODERNIZACION', null=True)),
                ('horario_inicio', models.DateTimeField(blank=True, db_column='HORARIO_INICIO', null=True)),
                ('horario_finalizacion', models.DateTimeField(blank=True, db_column='HORARIO_FINALIZACION', null=True)),
                ('nombre_lugar', models.CharField(blank=True, db_column='NOMBRE_LUGAR', max_length=70, null=True)),
            ],
            options={
                'db_table': 'visitas',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
