# Generated by Django 4.2 on 2023-05-16 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO djangoapp_role (name, description) VALUES ('Referente', 'El rol de referente es aquel que constestara las consultas que no puedan los Asesores'), ('Secretario/a', 'El rol de secretario/a es el encargado de agendar visitas y proveer informacion sobre ella'), ('Administrador', 'Este rol es capaz de hacer cualquier cosa en el sistema')")
        migrations.RunSQL("INSERT INTO djangoapp_faq (faq) ")
        migrations.RunSQL("INSERT INTO djangoapp_citydepartment (name, description) ")
        migrations.RunSQL("INSERT INTO djangoapp_locality (name, department_id)")
        migrations.RunSQL("INSERT INTO djangoapp_ministrydepartment (name, description)")
        migrations.RunSQL("INSERT INTO djangoapp_visitstatus (name, description)")
    ]
