# Generated by Django 4.2 on 2023-05-16 14:59
from sqlite3 import IntegrityError

import requests
from django.db import migrations
from django.db import transaction


def get_city_departments(app, *args):
    try:
        with transaction.atomic():
            CityDepartment = app.get_model('djangoapp', 'CityDepartment')
            URL = 'https://apis.datos.gob.ar/georef/api/departamentos?provincia=córdoba&campos=nombre&max=50'
            r = requests.get(URL)
            data = r.json()
            departamentos = []
            for d in data.get('departamentos'):
                departamento = CityDepartment(id=d.get("id"), name=d.get("nombre"), description=d.get("nombre"))
                departamentos.append(departamento)
            CityDepartment.objects.bulk_create(departamentos)
    except IntegrityError:
        print("--------------ERROR--------------")


def get_localities(app, *args):
    try:
        with transaction.atomic():
            Locality = app.get_model('djangoapp', 'Locality')
            URL = "https://apis.datos.gob.ar/georef/api/localidades?provincia=Córdoba&campos=nombre,departamento&max=1000"
            r = requests.get(URL)
            data = r.json()
            localidades = []
            for d in data.get("localidades"):
                localidad = Locality(name=d.get("nombre"), id_department_id=d.get("departamento").get("id"))
                localidades.append(localidad)
            Locality.objects.bulk_create(localidades)
    except IntegrityError:
        print("--------------ERROR--------------")


class Migration(migrations.Migration):
    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [

        migrations.RunPython(get_city_departments),

        migrations.RunPython(get_localities)

    ]

    """
     migrations.RunSQL("INSERT INTO djangoapp_citydepartment (name, description) ")
     migrations.RunSQL("INSERT INTO djangoapp_locality (name, department_id)")
     migrations.RunSQL("INSERT INTO djangoapp_mayor" (first_name, last_name)")
     migrations.RunSQL("INSERT INTO djangoapp_logo" (name, description)")
     migrations.RunSQL("INSERT INTO djangoapp_politicparty (name, description)")
     """
