# Generated by Django 4.2 on 2023-05-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_get_localities_and_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphone',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='id_verified_status',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='profile_picture',
            field=models.ImageField(default=None, upload_to='images/profile_pictures/'),
        ),
        migrations.DeleteModel(
            name='UserEmail',
        ),
        migrations.DeleteModel(
            name='UserPhone',
        ),
        migrations.DeleteModel(
            name='UserVerifiedStatus',
        ),
    ]
