# Generated by Django 4.2 on 2023-05-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_populate_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_picture',
            field=models.ImageField(default=None, upload_to='djangoapp/images/profile_pictures/'),
        ),
    ]
